### ISSUE TITLE
Stuck on 'Loading terrain...'

### ISSUE THREAD

**Issue by stantios** [dlee13/hold-that-chunk#12] opened 2022-11-05 21:55 UTC
Basically the title, here are my logs: https://mclo.gs/tbWBojG (Nether) https://mclo.gs/hz9JNbv (End)

This happened when I tried to go to a dimension through a portal either to the Nether or End.

**Comment by dlee13** [comment] 2022-11-06 12:42
After mapping the exception to yarn, we get:
```
[21:51:37] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.world.ClientWorld.getChunkManager()" because "this.world" is null
```

The null world was not caused by Hold That Chunk. It's an odd edge case to encounter though. Did you test the same thing on other servers?

**Comment by dlee13** [comment] 2022-11-06 13:12
I will probably have to push an update in which the chunk unload task returns early if the world is null. Could you additionally test whether the issue still occurs when Hold That Chunk and Quilted Fabric API are the only enabled mods?

**Comment by dlee13** [comment] 2022-11-06 13:30
Perhaps another mod is interacting somehow. Regardless, this should be fixed by adding a null check in Hold That Chunk. You could test it with the new build from:
https://github.com/dlee13/hold-that-chunk/actions/runs/3404524378

**Comment by dlee13** [comment] 2022-11-06 13:35
So it's not reliably reproducible, the worst type of thing to debug. lol

**Closed as completed** 2022-11-06 16:56 UTC
