### ISSUE TITLE
Missing parts of cached chunks

### ISSUE THREAD

**Issue by Madis0** [dlee13/hold-that-chunk#5] opened 2022-08-13 09:07 UTC
_This is a report on MeklanB's behalf before they commented here._

In HoldThatChunk v1.0.3 on Minecraft 1.19.2, there are visual artifacts and X-ray glitches in chunks that should be cached. These glitches are not present in a similar mod, [Farsight](https://www.curseforge.com/minecraft/mc-mods/farsight-fabric) and they appeared only when flying, not walking.

> Getting visual artifacts and missing surfaces (resulting in x-ray) when flying in and out of chunks that should be in memory.

Screenshot album: https://imgur.com/a/p5ReFeD

Note that these tests were conducted in the modpack [Fabulously Optimized](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) versions [4.2.0-beta.1](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3924583) (manually replaced Farsight with Hold That Chunk) and [4.2.0-beta.2](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3930919) (contains Hold That Chunk without Farsight). Unfortunately it is currently unknown whether this is reproducible with just Hold That Chunk, without the other mods.

**Comment by MeklanB** [comment] 2022-08-13 12:34
I'm not seeing these issues when testing Hold That Chunk in isolation in a vanilla MC instance. I'm going to start flipping through FO's mod list to see which may introduce issues.

**Comment by MeklanB** [comment] 2022-08-13 13:18
Confirmed the issues did not arise with Sodium, Lithium, MemoryLeakFix, or Starlight.

**Comment by dlee13** [comment] 2022-08-24 04:20
The chunks are in the chunk cache, but the level renderer may sometimes skip drawing chunks that are outside the effective render distance. The effective render distance is calculated by taking the minimum between the client render distance and the server render distance. Farsight would have the same behavior if you configure its max distance option to be the same as the server render distance.

**Comment by Madis0** [comment] 2022-08-24 15:54
What if Hold That Chunk used client render distance + constant to workaround this bug?

**Comment by dlee13** [comment] 2022-08-24 21:04
> Because it would still render by the client render distance, it shouldn't affect performance that much.

It will render by the effective render distance.

If you set `ignoreServerRenderDistance` to false, it follows vanilla behavior for calculating the effective render distance. The effective render distance is the lower value between client render distance and server render distance. If you set it true, it replaces the server render distance with the value of the client render distance, thereby making the effective render distance equal to client render distance.

The effective render distance is used for multiple things, including how far the level renderer will always draw chunks and where to place the fog.

**Comment by Madis0** [comment] 2022-11-06 13:19
Has this been fixed with 2.0.0?

**Comment by dlee13** [comment] 2022-11-06 13:22
It has not.

**Comment by Julienraptor01** [comment] 2022-12-23 22:48
could a solution be to only render chunk if all chunk between are rendered starting from the chunk the player stand in ?

like if you have the 8x8 circle which is the server distance then a missing empty chunk then a chunk the client know, don't render the one the client know because there is an empty chunk in between

**Comment by dlee13** [comment] 2023-10-25 08:56
In my testing, this is not an issue anymore. It was probably fixed by Sodium 0.5.0.

To begin with, this was a rendering bug and Hold That Chunk does nothing to the renderer.

**Closed by dlee13** 2023-10-25 08:56 UTC
Labels: help wanted
