### ISSUE TITLE
Support option to write cached chunks to disk to persist between sessions

### ISSUE THREAD

**Issue by nelsnelson** [dlee13/hold-that-chunk#20] opened 2023-04-13 23:40 UTC
# Persist chunks to disk

Support option to write cached chunks to disk to persist between sessions.

I would like to have all the chunks I download from the server persisted to disk.

This way, all the chunks I flew around collecting are not discarded when I quit and re-open the game to reconnect to the server for whatever reason.

## Fair-play

Some servers might have rules about not persisting chunks to disk.

Support a "fair-play" option to encrypt all downloaded server chunk data at rest, and decrypt to load into memory.

**Comment by dlee13** [comment] 2023-08-14 00:08
Duplicate of #16

**Closed by dlee13** 2023-08-14 00:08 UTC
