### ISSUE TITLE
Ignore server render distance doesn't enable unless on main menu

### ISSUE THREAD

**Issue by benjamin051000** [dlee13/hold-that-chunk#21] opened 2023-06-16 22:13 UTC
When attempting to enable the "Ignore server render distance" option while in a multiplayer session, the Enabled status of the button resets and the behavior does not change. It only actually enables from the main menu.

**Comment by dlee13** [comment] 2023-06-18 08:02
That is working as intended. The client sets the render distance upon receiving the login packet, so it takes rejoining the server for the change to take effect anyways.

**Comment by benjamin051000** [comment] 2023-06-18 15:35
There should be a warning message about what you said then, or the option should be greyed out when it is not available to be changed, rather than silently failing to enable. For players that don't understand how it works, they may be confused and think the mod isn't behaving correctly.

**Comment by dlee13** [comment] 2023-06-19 04:17
When you have YACL installed but not Cloth Config, the YACL screen is used and that option is disabled like you suggested. However, when you have Cloth Config installed, the Cloth Config screen is used instead. And Cloth Config doesn't have any API to disable options. I'll consider adding a tooltip to that or setting an error supplier.

**Comment by dlee13** [comment] 2023-10-25 07:57
Fixed in commit 95b356a5cad8c84a373c18a5d9beebf1174a2bb3

The option gets disabled when it cannot be changed.

**Closed by dlee13** 2023-10-25 07:57 UTC
